// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_z7hHLwtHaYrgv6JVkrUqYYyls5dxvc0',
    appId: '1:960295998759:web:ffd92ae729a8fa09340502',
    messagingSenderId: '960295998759',
    projectId: 'firebase-database-flutter',
    databaseURL: "https://firebase-database-flutter-default-rtdb.firebaseio.com",
    authDomain: 'fir-database-flutter-5142e.firebaseapp.com',
    storageBucket: 'firebase-database-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyn7WZnseu7dgKf4eQEjXTDD-og8GwC7I',
    appId: '1:960295998759:android:684b1f40da99529c340502',
    messagingSenderId: '960295998759',
    databaseURL: "https://firebase-database-flutter-default-rtdb.firebaseio.com",
    projectId: 'firebase-database-flutter',
    storageBucket: 'firebase-database-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0gz_NvVNgR3qezNPcthszACW2h5YUyc',
    appId: '1:960295998759:ios:de1b7634e011af75340502',
    messagingSenderId: '960295998759',
    projectId: 'firebase-database-flutter',
    databaseURL: "https://firebase-database-flutter-default-rtdb.firebaseio.com",
    storageBucket: 'firebase-database-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudExampleFlutter',
  );
}
